require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'PorcupineDemo' do
  config = use_native_modules!

  pod 'Porcupine-iOS', :podspec => 'https://raw.githubusercontent.com/Picovoice/porcupine/v2.0-rn/binding/ios/Porcupine-iOS.podspec'

  use_react_native!(:path => config["reactNativePath"])
end
