source 'https://cdn.cocoapods.org/'
platform :ios, '9.0'

target 'PorcupineForegroundAppDemo' do
    pod 'Porcupine-iOS', :path => '../../../'
end

target 'PorcupineForegroundAppDemoUITests' do
    pod 'Porcupine-iOS', :path => '../../../'
end
