source 'https://cdn.cocoapods.org/'
platform :ios, '9.0'

target 'PorcupineForegroundAppDemo' do
    pod 'Porcupine-iOS', :podspec => 'https://raw.githubusercontent.com/Picovoice/porcupine/ios-2.0/binding/ios/Porcupine-iOS.podspec'
end

target 'PorcupineForegroundAppDemoUITests' do
    pod 'Porcupine-iOS', :podspec => 'https://raw.githubusercontent.com/Picovoice/porcupine/ios-2.0/binding/ios/Porcupine-iOS.podspec'
end
