source 'https://cdn.cocoapods.org/'
platform :ios, '13.0'

target 'PorcupineAppTest' do
  pod 'Porcupine-iOS', '~> 3.0.1'
end

target 'PorcupineAppTestUITests' do
  pod 'Porcupine-iOS', '~> 3.0.1'
end

target 'PerformanceTest' do
  pod 'Porcupine-iOS', '~> 3.0.1'
end
