---
name: Bug report
about: Bugs in Porcupine
title: 'Porcupine Issue: '
labels: bug
assignees: ''

---

Make sure you have read the documentation, and have put forth a reasonable effort to find an existing answer.

### Expected behaviour


### Actual behaviour


### Steps to reproduce the behaviour

(Include enough details so that the issue can be reproduced independently.)
