[package]
name = "pv_porcupine_micdemo"
version = "0.1.0"
edition = "2018"

[dependencies]
clap = "2.33.3"
cpal = "0.13.3"
itertools = "0.10.1"
lazy_static = "1.4.0"
pv_porcupine = { path = "../../../binding/rust" }
ctrlc = "3.1.9"