[package]
name = "pv_porcupine_micdemo"
version = "3.0.0"
edition = "2018"

[dependencies]
chrono = "0.4.19"
clap = "2.33.3"
ctrlc = "3.1.9"
hound = "3.4.0"
itertools = "0.10.1"
pv_porcupine = "=3.0.1"
pv_recorder = "=1.2.1"
