[package]
name = "pv_porcupine_micdemo"
version = "0.1.0"
edition = "2018"

[dependencies]
clap = "2.33.3"
miniaudio = "0.10.0"
itertools = "0.10.1"
pv_porcupine = "1.9.0"
ctrlc = "3.1.9"
chrono = "0.4.19"