name: Run filedemo

inputs:
  access_key:
    required: true
  library_path:
    required: true
  model_path:
    required: true
  keyword_path:
    required: true
  sensitivity:
    default: 0.5
  audio_path:
    required: true

runs:
  using: "composite"
  steps:
  - run: >
      ./build/porcupine_demo_file
      -a ${{ inputs.access_key }}
      -l ${{ inputs.library_path }}
      -m ${{ inputs.model_path }}
      -k ${{ inputs.keyword_path }}
      -t ${{ inputs.sensitivity }}
      -w ${{ inputs.audio_path }}
    working-directory: demo/c
    shell: bash
