name: porcupine
description: A new flutter plugin project.
version: 1.9.0
author: Picovoice
homepage: https://picovoice.ai/

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  ffi: ^0.1.3
  path_provider: ^1.6.24
  flutter:
    sdk: flutter

  flutter_voice_processor:
    path: ../../../flutter-voice-processor

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: ai.picovoice.flutter.porcupine
        pluginClass: PorcupinePlugin
      ios:
        pluginClass: PorcupinePlugin

  assets:
    - ../../lib/common/porcupine_params.pv
    - ../../resources/keyword_files/android/porcupine_android.ppn
    - ../../resources/keyword_files/ios/porcupine_ios.ppn
