name: porcupine
description: A Flutter plugin for Picovoice's Porcupine wake word engine
version: 1.9.0
author: Picovoice
homepage: https://picovoice.ai/

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  ffi: ^0.1.3
  path_provider: ^1.6.24
  flutter:
    sdk: flutter

  flutter_voice_processor:
    path: ../../../flutter-voice-processor

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: ai.picovoice.flutter.porcupine
        pluginClass: PorcupinePlugin
      ios:
        pluginClass: PorcupinePlugin

  assets:
    - ../../lib/common/porcupine_params.pv
    - ../../resources/keyword_files/android/alexa_android.ppn
    - ../../resources/keyword_files/android/americano_android.ppn
    - ../../resources/keyword_files/android/blueberry_android.ppn
    - ../../resources/keyword_files/android/bumblebee_android.ppn
    - ../../resources/keyword_files/android/computer_android.ppn
    - ../../resources/keyword_files/android/grapefruit_android.ppn
    - ../../resources/keyword_files/android/grasshopper_android.ppn
    - ../../resources/keyword_files/android/hey google_android.ppn
    - ../../resources/keyword_files/android/hey siri_android.ppn
    - ../../resources/keyword_files/android/jarvis_android.ppn
    - ../../resources/keyword_files/android/ok google_android.ppn
    - ../../resources/keyword_files/android/picovoice_android.ppn
    - ../../resources/keyword_files/android/porcupine_android.ppn
    - ../../resources/keyword_files/android/terminator_android.ppn
    - ../../resources/keyword_files/ios/alexa_ios.ppn
    - ../../resources/keyword_files/ios/americano_ios.ppn
    - ../../resources/keyword_files/ios/blueberry_ios.ppn
    - ../../resources/keyword_files/ios/bumblebee_ios.ppn
    - ../../resources/keyword_files/ios/computer_ios.ppn
    - ../../resources/keyword_files/ios/grapefruit_ios.ppn
    - ../../resources/keyword_files/ios/grasshopper_ios.ppn
    - ../../resources/keyword_files/ios/hey google_ios.ppn
    - ../../resources/keyword_files/ios/hey siri_ios.ppn
    - ../../resources/keyword_files/ios/jarvis_ios.ppn
    - ../../resources/keyword_files/ios/ok google_ios.ppn
    - ../../resources/keyword_files/ios/picovoice_ios.ppn
    - ../../resources/keyword_files/ios/porcupine_ios.ppn
    - ../../resources/keyword_files/ios/terminator_ios.ppn
