source 'https://cdn.cocoapods.org/'
platform :ios, '9.0'

target 'PorcupineBackgroundServiceDemo' do
    pod 'Porcupine-iOS', :podspec => 'https://raw.githubusercontent.com/Picovoice/porcupine/v2.0/binding/ios/Porcupine-iOS.podspec'
    pod 'SwiftySound'
end
