name: porcupine_demo
description: Demonstrates how to use the porcupine plugin.

publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  flutter_picker: ^2.0.1
  path_provider: ^2.0.2
  porcupine: ^1.9.12
  
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/ananas_android.ppn
    - assets/himbeere_android.ppn
    - assets/porcupine_params_de.pv
    - assets/porcupine_params_fr.pv
    - assets/porcupine_params_es.pv
    - assets/leopardo_android.ppn
    - assets/framboise_android.ppn
  uses-material-design: true
