name: Android CI

on:
  push:
    branches: [ appcenter-actions-1 ]
#     paths: 
#       - 'demo/android/Activity/**'
#       - '!demo/android/Activity/README.md'
    
#   pull_request:
#     branches: [ master ]
#     paths: 
#       - 'demo/android/Activity/**'
#       - '!demo/android/Activity/README.md'

defaults:
  run:
    working-directory: demo/android/Activity
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.4.0
    - name: Install AppCenter CLI
      run: npm install -g appcenter-cli
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build app
      run: ./gradlew assembleDebug
    - name: Build androidTest
      run: ./gradlew assembleAndroidTest
    
  
