name: Angular

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - 'binding/angular/**'
      - '!binding/angular/README.md'
      - 'lib/**'
      - 'resources/**'
      - '.github/workflows/angular.yml'
  pull_request:
    branches: [ master ]
    paths:
      - 'binding/angular/**'
      - '!binding/angular/README.md'
      - 'lib/**'
      - 'resources/**'
      - '.github/workflows/angular.yml'

defaults:
  run:
    working-directory: binding/angular

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Pre-build dependencies
      run: npm install yarn

    - name: Install dependencies
      run: yarn install

    - name: Build
      run: yarn build porcupine-angular --prod

    - name: Lint
      run: yarn lint
