name: Angular Codestyle

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - '**/angular/*.js'
      - '**/angular/*.ts'
      - '.github/workflows/angular-codestyle.yml'
  pull_request:
    branches: [ master, 'v[0-9]+.[0-9]+' ]
    paths:
      - '**/angular/*.js'
      - '**/angular/*.ts'
      - '.github/workflows/angular-codestyle.yml'

jobs:
  check-angular-codestyle:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js lts/*
      uses: actions/setup-node@v3
      with:
        node-version: lts/*

    - name: Pre-build dependencies
      run: npm install yarn

    - name: Run Binding Linter
      run: yarn && yarn lint
      working-directory: binding/angular

    - name: Run Demo Linter
      run: yarn && yarn lint
      working-directory: demo/angular
