name: Angular

on:
  push:
    branches: [ master ]
    paths:
      - 'binding/angular/**'
      - '!binding/angular/README.md'
      - 'lib/**'
      - 'resources/**'
  pull_request:
    branches: [ master ]
    paths:
      - 'binding/angular/**'
      - '!binding/angular/README.md'
      - 'lib/**'
      - 'resources/**'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Pre-build dependencies
      run: npm install yarn
      working-directory: binding/angular

    - name: Install dependencies
      run: yarn install
      working-directory: binding/angular

    - name: Build
      run: yarn build porcupine-web-angular --prod
      working-directory: binding/angular
