name: .NET VUI Demos

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - 'demo/dotnet-vui/**'
      - '!demo/dotnet-vui/README.md'
      - '.github/workflows/dotnet-vui-demos.yml'
  pull_request:
    branches: [ master, 'v[0-9]+.[0-9]+' ]
    paths:
      - 'demo/dotnet-vui/**'
      - '!demo/dotnet-vui/README.md'
      - '.github/workflows/dotnet-vui-demos.yml'

defaults:
  run:
    working-directory: demo/dotnet-vui/

jobs:
  build-vui-demo:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v3

    - name: Set up .NET 6.0
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Package restore
      run: dotnet restore

    - name: Dotnet build
      run: dotnet build
