name: Go

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - '**/*.go'
  pull_request:
    branches: [ master ]
    paths:
      - '**/*.go'

jobs:
  check-go-codestyle:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go: [ '1.16', '1.17', '1.18']

    steps:
    - uses: actions/checkout@v2

    - name: Setup go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3
