name: Go Demos

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - 'demo/go/**'
      - '!demo/go/README.md'
      - '.github/workflows/go-demos.yml'
  pull_request:
    branches: [ master, 'v[0-9]+.[0-9]+' ]
    paths:
      - 'demo/go/**'
      - '!demo/go/README.md'
      - '.github/workflows/go-demos.yml'


defaults:
  run:
    working-directory: demo/go

jobs:
  build-github-hosted:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        go: [ '1.16', '1.17', '1.18' ]

    steps:
    - uses: actions/checkout@v3

    - name: Set up go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go }}

    - name: Build micdemo
      run: go build micdemo/porcupine_mic_demo.go
      
    - name: Build filedemo
      run: go build filedemo/porcupine_file_demo.go

    - name: Test filedemo
      run: ./porcupine_file_demo -access_key ${{secrets.PV_VALID_ACCESS_KEY}} -input_audio_path ../../resources/audio_samples/multiple_keywords.wav -keywords picovoice

  build-self-hosted:
    runs-on: ${{ matrix.machine }}

    strategy:
      matrix:
        machine: [rpi3-32, rpi3-64, rpi4-32, rpi4-64, jetson]

    steps:
    - uses: actions/checkout@v3

    - name: Build micdemo
      run: go build micdemo/porcupine_mic_demo.go
      
    - name: Build filedemo
      run: go build filedemo/porcupine_file_demo.go

    - name: Test filedemo
      run: ./porcupine_file_demo -access_key ${{secrets.PV_VALID_ACCESS_KEY}} -input_audio_path ../../resources/audio_samples/multiple_keywords.wav -keywords picovoice

