name: Java Demos

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - 'demo/java/**'
      - '!demo/java/README.md'
      - '.github/workflows/java-demos.yml'
  pull_request:
    branches: [ master ]
    paths:
      - 'demo/java/**'
      - '!demo/java/README.md'
      - '.github/workflows/java-demos.yml'

defaults:
  run:
    working-directory: demo/java

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b

    - name: Build
      run: ./gradlew build
