name: JavaScript Codestyle

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - '**/*.js'
      - '**/*.ts'
      - '**/*.jsx'
      - '**/*.tsx'
      - '.github/workflows/js-codestyle.yml'
  pull_request:
    branches: [ master ]
    paths:
      - '**/*.js'
      - '**/*.ts'
      - '**/*.jsx'
      - '**/*.tsx'
      - '.github/workflows/js-codestyle.yml'

jobs:
  check-web-codestyle:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js lts/*
      uses: actions/setup-node@v2
      with:
        node-version: lts/*

    - name: Pre-build dependencies
      run: npm install yarn

    - name: Run Binding Linter
      run: yarn && yarn lint
      working-directory: binding/flutter

    - name: Run Demo Linter
      run: yarn && yarn lint
      working-directory: demo/flutter

  check-angular-codestyle:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js lts/*
      uses: actions/setup-node@v2
      with:
        node-version: lts/*

    - name: Pre-build dependencies
      run: npm install yarn

    - name: Run Binding Linter
      run: yarn && yarn lint
      working-directory: binding/angular

    - name: Run Demo Linter
      run: yarn && yarn lint
      working-directory: demo/angular

  check-react-codestyle:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js lts/*
      uses: actions/setup-node@v2
      with:
        node-version: lts/*

    - name: Pre-build dependencies
      run: npm install yarn

    - name: Run Binding Linter
      run: yarn && yarn lint
      working-directory: binding/react

    - name: Run Demo Linter
      run: yarn && yarn lint
      working-directory: demo/react

  check-vue-codestyle:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js lts/*
      uses: actions/setup-node@v2
      with:
        node-version: lts/*

    - name: Pre-build dependencies
      run: npm install yarn

    - name: Run Binding Linter
      run: yarn && yarn lint
      working-directory: binding/vue

    - name: Run Demo Linter
      run: yarn && yarn lint
      working-directory: demo/vue

  check-react-native-codestyle:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js lts/*
      uses: actions/setup-node@v2
      with:
        node-version: lts/*

    - name: Pre-build dependencies
      run: npm install yarn

    - name: Run Binding Linter
      run: yarn && yarn lint
      working-directory: binding/react-native

    - name: Run Demo Linter
      run: yarn && yarn lint
      working-directory: demo/react-native

  check-nodejs-codestyle:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js lts/*
      uses: actions/setup-node@v2
      with:
        node-version: lts/*

    - name: Pre-build dependencies
      run: npm install yarn

    - name: Run Binding Linter
      run: yarn && yarn lint
      working-directory: binding/nodejs
