name: Python

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - '**/*.py'
  pull_request:
    branches: [ master ]
    paths:
      - '**/*.py'

jobs:
  check-python-codestyle:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install pycodestyle

    - name: Check python codestyle
      run: pycodestyle . --max-line-length=120
