name: React Codestyle

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - '**/react/*.js'
      - '**/react/*.ts'
      - '**/react/*.jsx'
      - '**/react/*.tsx'
      - '.github/workflows/react-codestyle.yml'
  pull_request:
    branches: [ master ]
    paths:
      - '**/react/*.js'
      - '**/react/*.ts'
      - '**/react/*.jsx'
      - '**/react/*.tsx'
      - '.github/workflows/react-codestyle.yml'

jobs:
  check-react-codestyle:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js lts/*
      uses: actions/setup-node@v2
      with:
        node-version: lts/*

    - name: Pre-build dependencies
      run: npm install yarn

    - name: Run Binding Linter
      run: yarn && yarn lint
      working-directory: binding/react

    - name: Run Demo Linter
      run: yarn && yarn lint
      working-directory: demo/react
