name: Rust Demos

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - '.github/workflows/rust-demos.yml'
      - 'demo/rust/**'
      - '!demo/rust/README.md'
  pull_request:
    branches: [ master, 'v[0-9]+.[0-9]+' ]
    paths:
      - '.github/workflows/rust-demos.yml'
      - 'demo/rust/**'
      - '!demo/rust/README.md'

env:
  CARGO_TERM_COLOR: always

jobs:
  build-micdemo:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: demo/rust/micdemo

    steps:
    - uses: actions/checkout@v3

    - name: Rust dependencies
      run: sudo apt install libasound2-dev

    - name: Rust build micdemo
      run: cargo build --verbose

  build-filedemo:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: demo/rust/filedemo

    steps:
    - uses: actions/checkout@v3

    - name: Rust dependencies
      run: sudo apt install libasound2-dev

    - name: Rust build filedemo
      run: cargo build --verbose

    - name: Test
      run: cargo run --release -- --access_key ${{secrets.PV_VALID_ACCESS_KEY}} --input_audio_path ../../../resources/audio_samples/multiple_keywords.wav --keywords picovoice
