name: Rust

on:
  workflow_dispatch:
  push:
    branches: [ master, v2.0 ]
    paths:
      - 'binding/rust/**'
      - '!binding/rust/README.md'
      - 'lib/**'
      - 'res/**'
  pull_request:
    branches: [ master, v2.0 ]
    paths:
      - 'binding/rust/**'
      - '!binding/rust/README.md'
      - 'lib/**'
      - 'res/**'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Rust dependencies
      run: sudo apt install libasound2-dev

    - name: Rust pre-build
      run: ./copy.sh
      working-directory: binding/rust

    - name: Rust build
      run: cargo build --verbose
      working-directory: binding/rust

    - name: Rust run tests
      run: PV_ACCESS_KEY=${{secrets.PV_VALID_ACCESS_KEY}} cargo test --verbose
      working-directory: binding/rust
