name: Swift

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - '**/*.swift'
  pull_request:
    branches: [ master ]
    paths:
      - '**/*.swift'

jobs:
  check-switch-codestyle:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Check swift codestyle
      run: ./resources/lint/swift/swiftlint lint --config resources/lint/swift/.swiftlint.yml --strict
