name: Unity

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - 'binding/unity/**'
      - '!binding/unity/README.md'
      - 'lib/android/**'
      - 'lib/ios/**'
      - 'lib/linux/**'
      - 'lib/mac/**'
      - 'lib/windows/**'
      - 'resources/**'
      - '.github/workflows/unity.yml'
  pull_request:
    branches: [ master ]
    paths:
      - 'binding/unity/**'
      - '!binding/unity/README.md'
      - 'lib/android/**'
      - 'lib/ios/**'
      - 'lib/linux/**'
      - 'lib/mac/**'
      - 'lib/windows/**'
      - 'resources/**'
      - '.github/workflows/unity.yml'

defaults:
  run:
    working-directory: binding/unity

jobs:
  playtest-linux:
    name: Run PlayTest unit tests on ${{ matrix.platform }}
    runs-on: pv-android
    strategy:
      matrix:
        platform: ['StandaloneLinux64']

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - name: Pre-build dependencies
      run: |
        ./copy.sh
        ./copy_test_resources.sh

    - name: Inject AppID
      run: sed -i 's:{TESTING_ACCESS_KEY_HERE}:${{secrets.PV_VALID_ACCESS_KEY}}:'
        Assets/Porcupine/Tests/Integration.cs

    - name: Run tests
      run: xvfb-run --auto-servernum --server-args='-screen 0 640x480x24'
        /home/picovoice/Unity/Hub/Editor/2019.4.34f1/Editor/Unity -runTests -batchmode -projectPath . -testResults unityresults.xml -testPlatform ${{ matrix.platform }} -logFile -

    - name: Check Results
      run: sed -n 2p unityresults.xml | grep 'result="Passed"'

  playtest-mac-ios:
    name: Run PlayTest unit tests on ${{ matrix.platform }}
    runs-on: pv-ios
    strategy:
      matrix:
        platform: ['StandaloneOSX', 'iOS']

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - name: Pre-build dependencies
      run: |
        ./copy.sh
        ./copy_test_resources.sh

    - name: Clean conflicting dylib
      run: rm -rf Assets/Porcupine/Plugins/mac/arm64

    - name: Inject AppID
      run: sed -i '.bak' 's:{TESTING_ACCESS_KEY_HERE}:${{secrets.PV_VALID_ACCESS_KEY}}:'
        Assets/Porcupine/Tests/Integration.cs

    - name: Run tests
      run: /Applications/Unity/Hub/Editor/2019.4.34f1/Unity.app/Contents/MacOS/Unity -runTests -batchmode -projectPath . -testResults unityresults.xml -testPlatform ${{ matrix.platform }} -logFile - || echo "Run potentially failed - checking results anyways"

    - name: Check Results
      run: sed -n 2p unityresults.xml | grep 'result="Passed"'

  playtest-android:
    name: Run PlayTest unit tests on ${{ matrix.platform }}
    runs-on: pv-ios
    strategy:
      matrix:
        platform: ['Android']

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - name: Pre-build dependencies
      run: |
        ./copy.sh
        ./copy_test_resources.sh

    - name: Clean conflicting dylib
      run: rm -rf Assets/Porcupine/Plugins/mac/arm64

    - name: Inject AppID
      run: sed -i '.bak' 's:{TESTING_ACCESS_KEY_HERE}:${{secrets.PV_VALID_ACCESS_KEY}}:'
        Assets/Porcupine/Tests/Integration.cs

    - name: Start Emulator
      run: /Users/alirezakenarsari-anhari/Library/Android/sdk/emulator/emulator -avd Pixel_6_API_33 &

    - name: Run tests
      run: /Applications/Unity/Hub/Editor/2019.4.34f1/Unity.app/Contents/MacOS/Unity -runTests -batchmode -projectPath . -testResults unityresults.xml -testPlatform ${{ matrix.platform }} -logFile - || echo "Run potentially failed - checking results anyways"

    - name: Check Results
      run: sed -n 2p unityresults.xml | grep 'result="Passed"'
