name: Vue Demos

on:
  push:
    branches: [ master ]
    paths:
      - 'demo/vue/**'
      - '!demo/vue/README.md'
      - '.github/workflows/vue-demos.yml'
  pull_request:
    branches: [ master ]
    paths:
      - 'demo/vue/**'
      - '!demo/vue/README.md'
      - '.github/workflows/vue-demos.yml'

defaults:
  run:
    working-directory: demo/vue

jobs:
  build-demos:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Pre-build dependencies
      run: npm install yarn

    - name: Install dependencies
      run: yarn install

    - name: Build
      run: yarn build
