name: Web Demos

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - 'demo/web/**'
      - '!demo/web/README.md'
      - '.github/workflows/web-demos.yml'
  pull_request:
    branches: [ master, 'v[0-9]+.[0-9]+' ]
    paths:
      - 'demo/web/**'
      - '!demo/web/README.md'
      - '.github/workflows/web-demos.yml'

defaults:
  run:
    working-directory: demo/web

jobs:
  build:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: ${{ matrix.shell }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [14.x, 16.x, 18.x, 20.x]
        include:
          - os: ubuntu-latest
            shell: bash
          - os: windows-latest
            shell: cmd
          - os: macos-latest
            shell: bash

    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Pre-build dependencies
      run: npm install yarn

    - name: Install dependencies
      run: yarn install
    
    - name: Install pm2
      run: npm install pm2

    - name: Run Demo English
      run: npx pm2 start yarn -- start en

    - name: Run Demo Other Language
      run: npx pm2 start yarn -- start es

    - name: Stop servers
      run: npx pm2 delete all
